language: node_js
before-install:
  - npm install npm -g
  - npm install grunt -g
install:
  - make download
script:
  - make
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "mathjax.zip"
  skip_cleanup: true
  on:
    tags: true
