language: node_js
install:
    - make download
    - npm install npm -g
script:
    - make
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "mathjax.zip"
  skip_cleanup: true
  on:
    tags: true
